# PicPose app-specific R8 rules
#
# Design goal:
# - Stability first for release runtime paths (Home/Auth/Ads/Guides).
# - Keep only app-specific rules that are not already supplied by library
#   consumer rules.
# - Avoid broad keep-all patterns that unnecessarily bloat APK size.

# ------------------------------------------------------------
# 1) Shared Metadata Needed By Reflection/Serialization
# ------------------------------------------------------------
# Preserve metadata required by Retrofit/Gson/Moshi and Kotlin reflection paths.
-keepattributes Signature, InnerClasses, EnclosingMethod, AnnotationDefault
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations

# ------------------------------------------------------------
# 2) Android Framework Entry Points
# ------------------------------------------------------------
# Android entry points instantiated by the framework (manifest + system callbacks).
-keep class * extends android.app.Application
-keep class * extends android.app.Service
-keep class * extends android.content.BroadcastReceiver
-keep class * extends android.content.ContentProvider

# ------------------------------------------------------------
# 3) App-Level Keep Contracts
# ------------------------------------------------------------
# Respect explicit @Keep annotations used in app models/contracts.
-keep @androidx.annotation.Keep class * { *; }
-keepclasseswithmembers class * {
    @androidx.annotation.Keep <fields>;
}
-keepclasseswithmembers class * {
    @androidx.annotation.Keep <methods>;
}

# ------------------------------------------------------------
# 4) Retrofit/Gson/Moshi
# ------------------------------------------------------------
# Retrofit interfaces are invoked via dynamic proxies.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# App API models (critical for Gson reflection in Home/Auth/Guides/Ads flows).
# Keep these classes and members stable to avoid release-only JSON parse regressions.
-keep class com.picpose.bestphotographyapp.data.remote.dto.** { *; }
-keep class com.picpose.bestphotographyapp.data.remote.response.** { *; }

# Gson model field mapping.
-keepclassmembers,allowobfuscation class * {
    @com.google.gson.annotations.SerializedName <fields>;
}

# Gson TypeToken generic signatures (used in Room converters and JSON helpers).
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

# Moshi reflection model used by Twitter OAuth token exchange.
-keepclassmembers class com.picpose.bestphotographyapp.data.remote.auth.TwitterTokenResponse {
    <fields>;
}

# ------------------------------------------------------------
# 5) Hilt / Firebase / Ads / Play Services
# ------------------------------------------------------------
# Hilt, Firebase, Google Play services, Compose, Room, Coil, and AdMob artifacts
# ship consumer ProGuard rules. No additional broad keep rules are needed here.
#
# Meta Audience Network (transitive optional annotation dependency).
# Generated by R8 missing_rules.txt for current FAN SDK.
-dontwarn com.facebook.infer.annotation.Nullsafe
-dontwarn com.facebook.infer.annotation.Nullsafe$Mode

# ------------------------------------------------------------
# 6) Parcelable / Navigation Payload Safety
# ------------------------------------------------------------
# Preserve Parcelable creator fields for parcel/unparcel flows.
-keepclassmembers class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}

# ------------------------------------------------------------
# 7) Release-Only Log Stripping
# ------------------------------------------------------------
# Strip Android log calls in release builds.
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
    public static *** w(...);
    public static *** e(...);
}

# Optional: silence OkHttp logging interceptor output in release.
-assumenosideeffects class okhttp3.logging.HttpLoggingInterceptor$Logger {
    public void log(...);
}
